/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { DialogueNode, Evidence } from './types';

export const ALL_EVIDENCE: Record<string, Evidence> = {
  'water_report': {
    id: 'water_report',
    name: 'Báo cáo xét nghiệm nguồn nước',
    description: 'Kết quả phân tích cho thấy nồng độ kim loại nặng và hóa chất độc hại vượt mức cho phép gấp 100 lần.',
    image: 'https://i.postimg.cc/RhQggXsw-/bc1.png',
  },
  'dolphin_report': {
    id: 'dolphin_report',
    name: 'Báo cáo xét nghiệm cá heo',
    description: 'Báo cáo khám nghiệm xác cá heo dạt vào bờ, phát hiện dư lượng hóa chất bảo quản gỗ trong nội tạng.',
    image: 'https://i.postimg.cc/zfF3XhcJ/bc2.png',
  },
  'petition': {
    id: 'petition',
    name: 'Đơn kiến nghị từ người dân',
    description: 'Tập hồ sơ chứa chữ ký của hơn 500 hộ dân vùng hạ lưu tố cáo việc xả thải lén lút vào ban đêm.',
    image: 'https://i.postimg.cc/G3WKZBZC/Chat-GPT-Image-May-4-2026-01-22-48-AM.png',
  },
  'payroll_ledger': {
    id: 'payroll_ledger',
    name: 'Sổ cái quỹ đen',
    description: 'Cuốn sổ ghi chép các khoản chi hối lộ cho các cán bộ phụ trách kiểm tra môi trường khu vực.',
    image: 'https://i.postimg.cc/VL0qs7Bt/Chat-GPT-Image-May-4-2026-01-21-45-AM.png',
  },
  'chemical_receipt': {
    id: 'chemical_receipt',
    name: 'Hóa đơn hóa chất cấm',
    description: 'Hóa đơn nhập khẩu một lượng lớn chất H-404, loại hóa chất cực độc đã bị cấm sử dụng trong công nghiệp.',
    image: 'https://i.postimg.cc/76PhCLFS/hoadon.png',
  },
  'fish_license': {
    id: 'fish_license',
    name: 'Thẻ thanh tra',
    description: 'Thẻ hành nghề của Thanh tra Thiện. Nó chứng minh ông có quyền điều tra và đứng tại đây tố cáo.',
    image: 'https://i.postimg.cc/W1HhHZHM/Chat-GPT-Image-May-4-2026-01-26-38-AM.png',
  }
};

export const DIALOGUE_TREE: Record<string, DialogueNode> = {
  'intro_1': {
    id: 'intro_1',
    speaker: 'Thẩm Phán',
    text: 'Phiên tòa bắt đầu! Hôm nay chúng ta xét xử vụ kiện nghiêm trọng: Thanh tra Thiện tố cáo bà Ngọc, chủ nhà máy gỗ, về tội hủy hoại môi trường.',
    emotion: 'normal',
    background: 'https://i.postimg.cc/kMcHqH4R/neu.png',
    characterImage: 'https://i.pinimg.com/1200x/4b/9a/c3/4b9ac31ce1d2a08852e9e0877350bfde.jpg',
    nextId: 'intro_decision',
  },
  'intro_decision': {
    id: 'intro_decision',
    speaker: 'Thanh tra Thiện',
    text: '(Hôm nay mình phải đưa sự thật ra ánh sáng. Mình nên làm gì trước đây?)',
    emotion: 'thinking',
    background: 'https://i.postimg.cc/q7wm4hBd/Gemini-Generated-Image-lj58e4lj58e4lj58.png',
    characterImage: 'https://i.postimg.cc/ZqcgfsXp/thien1.png',
    choices: [
      { text: 'Bắt đầu tố cáo', nextId: 'intro_2' },
      { text: 'Kiểm tra bằng chứng', nextId: 'intro_decision', action: 'OPEN_DOSSIER' }
    ]
  },
  'intro_2': {
    id: 'intro_2',
    speaker: 'Thanh tra Thiện',
    text: 'Thưa tòa! Tôi đã thu thập đủ bằng chứng cho thấy nhà máy của bà Ngọc đã làm ô nhiễm nghiêm trọng nguồn nước khu vực này.',
    emotion: 'angry',
    background: 'https://i.postimg.cc/q7wm4hBd/Gemini-Generated-Image-lj58e4lj58e4lj58.png',
    characterImage: 'https://i.postimg.cc/ZqcgfsXp/thien1.png',
    nextId: 'court_start',
  },
  'court_start': {
    id: 'court_start',
    speaker: 'Thẩm Phán',
    text: 'Bà Ngọc, bà có tuyên bố gì về những cáo buộc liên quan đến việc xả thải trái phép gây ô nhiễm không?',
    emotion: 'normal',
    background: 'https://i.postimg.cc/kMcHqH4R/neu.png',
    characterImage: 'https://i.pinimg.com/1200x/4b/9a/c3/4b9ac31ce1d2a08852e9e0877350bfde.jpg',
    nextId: 'cross_exam_1',
  },
  'cross_exam_1': {
    id: 'cross_exam_1',
    speaker: 'Bà Ngọc',
    text: 'Nhà máy tôi hoạt động cực kỳ minh bạch và luôn được các đoàn kiểm tra đánh giá cao về ý thức bảo vệ môi trường.',
    emotion: 'happy',
    background: 'https://i.postimg.cc/MptvzqQh/villain4-21.png',
    characterImage: 'https://i.postimg.cc/jjYFcY2R/vilain4-1.png',
    isStatement: true,
    correctEvidence: 'payroll_ledger',
    onCorrectionId: 'objection_1',
    nextId: 'cross_exam_2',
  },
  'objection_1': {
    id: 'objection_1',
    speaker: 'Thanh tra Thiện',
    text: 'ĐƯỢC ĐÁNH GIÁ CAO SAO? Vậy bà giải thích thế nào về cuốn "Sổ cái quỹ đen" này? Trong này ghi rõ các khoản bà đã chi để hối lộ cán bộ kiểm tra!',
    emotion: 'surprised',
    background: 'https://i.postimg.cc/Hx2FvYPJ/thien2.png',
    characterImage: 'https://i.postimg.cc/ZqcgfsXp/thien1.png',
    nextId: 'defendant_shocked_1',
  },
  'defendant_shocked_1': {
    id: 'defendant_shocked_1',
    speaker: 'Bà Ngọc',
    text: 'Đó... đó chỉ là tiền hỗ trợ xăng xe cho các anh ấy đi lại vất vả thôi! Nó không chứng minh được tôi có tội xả thải!',
    emotion: 'angry',
    background: 'https://i.postimg.cc/Wzt8TTSn/Chat-GPT-Image-00-54-20-4-thg-5-2026.png',
    characterImage: 'https://i.postimg.cc/jjYFcY2R/vilain4-1.png',
    nextId: 'cross_exam_2',
  },
  'cross_exam_2': {
    id: 'cross_exam_2',
    speaker: 'Bà Ngọc',
    text: 'Hơn nữa, hệ thống camera giám sát của chúng tôi hoạt động 24/7 và không hề ghi nhận bất kỳ sự cố xả thải bất thường nào.',
    emotion: 'happy',
    background: 'https://i.postimg.cc/MptvzqQh/villain4-21.png',
    characterImage: 'https://i.postimg.cc/jjYFcY2R/vilain4-1.png',
    isStatement: true,
    correctEvidence: 'petition',
    onCorrectionId: 'objection_2',
    nextId: 'cross_exam_3',
  },
  'objection_2': {
    id: 'objection_2',
    speaker: 'Thanh tra Thiện',
    text: 'CAMERA CÓ THỂ BỊ TẮT, NHƯNG MẮT DÂN THÌ KHÔNG! Hãy xem đơn kiến nghị của 500 hộ dân này. Họ đã tận mắt thấy nhà máy xả nước đen kịt vào rừng đêm!',
    emotion: 'surprised',
    background: 'https://i.postimg.cc/Hx2FvYPJ/thien2.png',
    characterImage: 'https://i.postimg.cc/ZqcgfsXp/thien1.png',
    nextId: 'defendant_shocked_2',
  },
  'defendant_shocked_2': {
    id: 'defendant_shocked_2',
    speaker: 'Bà Ngọc',
    text: 'Hừ! Một lũ dân nghèo ghen ăn tức ở thì biết cái gì? Họ chỉ đang cố tống tiền doanh nghiệp chúng tôi mà thôi!',
    emotion: 'angry',
    background: 'https://i.postimg.cc/Wzt8TTSn/Chat-GPT-Image-00-54-20-4-thg-5-2026.png',
    characterImage: 'https://i.postimg.cc/jjYFcY2R/vilain4-1.png',
    nextId: 'cross_exam_3',
  },
  'cross_exam_3': {
    id: 'cross_exam_3',
    speaker: 'Bà Ngọc',
    text: 'Các anh cứ làm quá lên! Những nguồn nước thải từ nhà máy tôi đã qua xử lý, hoàn toàn không có ảnh hưởng gì đến các sinh vật hay môi trường sinh thái cả!',
    emotion: 'normal',
    background: 'https://i.postimg.cc/MptvzqQh/villain4-21.png',
    characterImage: 'https://i.postimg.cc/jjYFcY2R/vilain4-1.png',
    isStatement: true,
    correctEvidence: 'dolphin_report',
    onCorrectionId: 'objection_3',
    nextId: 'cross_exam_4',
  },
  'objection_3': {
    id: 'objection_3',
    speaker: 'Thanh tra Thiện',
    text: 'KHÔNG CÓ ẢNH HƯỞNG?! Vậy bà giải thích sao về mẫu xét nghiệm cá heo chết dạt vào bờ này? Nó đã chết thảm khốc với nồng độ độc chất của ngành gỗ cực cao trong nội tạng!',
    emotion: 'surprised',
    background: 'https://i.postimg.cc/Hx2FvYPJ/thien2.png',
    characterImage: 'https://i.postimg.cc/ZqcgfsXp/thien1.png',
    nextId: 'defendant_shocked_3',
  },
  'defendant_shocked_3': {
    id: 'defendant_shocked_3',
    speaker: 'Bà Ngọc',
    text: 'Đó... đó chỉ là một trường hợp cá biệt! Biết đâu con cá đó bơi từ vùng biển ô nhiễm khác tới đây thì sao?',
    emotion: 'thinking',
    background: 'https://i.postimg.cc/Wzt8TTSn/Chat-GPT-Image-00-54-20-4-thg-5-2026.png',
    characterImage: 'https://i.postimg.cc/jjYFcY2R/vilain4-1.png',
    nextId: 'cross_exam_4',
  },
  'cross_exam_4': {
    id: 'cross_exam_4',
    speaker: 'Bà Ngọc',
    text: 'Tôi khẳng định lại một lần nữa: Nhà máy tôi chỉ sử dụng các loại thuốc tẩy rửa thân thiện, hoàn toàn không chứa bất kỳ chất cấm nào!',
    emotion: 'happy',
    background: 'https://i.postimg.cc/MptvzqQh/villain4-21.png',
    characterImage: 'https://i.postimg.cc/jjYFcY2R/vilain4-1.png',
    isStatement: true,
    correctEvidence: 'chemical_receipt',
    onCorrectionId: 'objection_4',
    nextId: 'cross_exam_5',
  },
  'objection_4': {
    id: 'objection_4',
    speaker: 'Thanh tra Thiện',
    text: 'THÂN THIỆN?! Hãy nhìn hóa đơn này! Tháng trước, bà đã nhập khẩu trái phép 5 tấn H-404 - loại hóa chất kịch độc đã bị cấm!',
    emotion: 'surprised',
    background: 'https://i.postimg.cc/Hx2FvYPJ/thien2.png',
    characterImage: 'https://i.postimg.cc/ZqcgfsXp/thien1.png',
    nextId: 'defendant_shocked_4',
  },
  'defendant_shocked_4': {
    id: 'defendant_shocked_4',
    speaker: 'Bà Ngọc',
    text: 'Đúng, tôi có mua H-404, nhưng tôi dùng nó để diệt mối trong nền móng tòa nhà, không hề để nó tiếp xúc với nguồn nước sông!',
    emotion: 'angry',
    background: 'https://i.postimg.cc/Wzt8TTSn/Chat-GPT-Image-00-54-20-4-thg-5-2026.png',
    characterImage: 'https://i.postimg.cc/jjYFcY2R/vilain4-1.png',
    nextId: 'rebuttal_climax',
  },
  'rebuttal_climax': {
    id: 'rebuttal_climax',
    speaker: 'Bà Ngọc',
    text: 'Dòng sông bị ô nhiễm có thể là do rác thải từ nơi khác tới. Cậu Thiện, cậu lấy gì chứng minh độc chất dưới sông kia chính là H-404 của tôi?',
    emotion: 'happy',
    background: 'https://i.postimg.cc/MptvzqQh/villain4-21.png',
    characterImage: 'https://i.postimg.cc/jjYFcY2R/vilain4-1.png',
    nextId: 'cross_exam_5',
  },
  'cross_exam_5': {
    id: 'cross_exam_5',
    speaker: 'Bà Ngọc',
    text: 'Nguồn nước sông hiện tại tuy có chút vấn đề nhưng đó là do ô nhiễm chung của cả vùng, chẳng liên quan gì đến hóa chất của tôi!',
    emotion: 'normal',
    background: 'https://i.postimg.cc/MptvzqQh/villain4-21.png',
    characterImage: 'https://i.postimg.cc/jjYFcY2R/vilain4-1.png',
    isStatement: true,
    correctEvidence: 'water_report',
    onCorrectionId: 'objection_5',
    nextId: 'thinking_climax',
  },
  'objection_5': {
    id: 'objection_5',
    speaker: 'Thanh tra Thiện',
    text: 'ĐÂY CHÍNH LÀ CÂU TRẢ LỜI! Báo cáo xét nghiệm này chỉ rõ: Độc chất dưới sông CHÍNH LÀ H-404 với đặc điểm trùng khớp mẫu tại nhà máy bà!',
    emotion: 'surprised',
    background: 'https://i.postimg.cc/Hx2FvYPJ/thien2.png',
    characterImage: 'https://i.postimg.cc/ZqcgfsXp/thien1.png',
    nextId: 'villain_breakdown',
  },
  'villain_breakdown': {
    id: 'villain_breakdown',
    speaker: 'Bà Ngọc',
    text: 'Cái gì... Sao có thể... Kết quả xét nghiệm lại nhanh như vậy được... Tôi đã trả tiền để họ trì hoãn nó rồi mà!',
    emotion: 'thinking',
    background: 'https://i.postimg.cc/Hn14MXtB/villain5.png',
    characterImage: 'https://i.postimg.cc/jjYFcY2R/vilain4-1.png',
    nextId: 'final_choice',
  },
  'final_choice': {
    id: 'final_choice',
    speaker: 'Thanh tra Thiện',
    text: '(Bà ta vừa tự lỡ lời kìa! Bây giờ là lúc dùng suy luận để kết thúc vụ án!)',
    emotion: 'thinking',
    background: 'https://i.postimg.cc/fR9QKh7N/Chat-GPT-Image-23-52-58-3-thg-5-2026.png',
    characterImage: 'https://i.postimg.cc/ZqcgfsXp/thien1.png',
    choices: [
      { text: 'Chỉ ra sự lỡ lời về việc hối lộ', nextId: 'reasoning_correct' },
      { text: 'Nói về sự phẫn nộ của người dân', nextId: 'villain_laugh' }
    ]
  },
  'reasoning_correct': {
    id: 'reasoning_correct',
    speaker: 'Thanh tra Thiện',
    text: 'THƯA TÒA! Bà ta vừa thừa nhận đã cố tình "trì hoãn kết quả xét nghiệm". Bà ta đã tự thú về hành vi che giấu tội lỗi của mình!',
    emotion: 'surprised',
    background: 'https://i.postimg.cc/Hx2FvYPJ/thien2.png',
    characterImage: 'https://i.postimg.cc/ZqcgfsXp/thien1.png',
    nextId: 'villain_defeated',
  },
  'villain_defeated': {
    id: 'villain_defeated',
    speaker: 'Bà Ngọc',
    text: 'KHÔNG! Tôi không có ý đó! Thẩm phán... làm ơn... tôi chỉ là...',
    emotion: 'thinking',
    background: 'https://i.postimg.cc/Hn14MXtB/villain5.png',
    characterImage: 'https://i.postimg.cc/jjYFcY2R/vilain4-1.png',
    nextId: 'win_case',
  },
  'villain_laugh': {
    id: 'villain_laugh',
    speaker: 'Bà Ngọc',
    text: 'Ha ha! Cậu quá non nớt rồi Thiện ạ. Những suy luận cảm tính đó không thể đứng vững trước tòa đâu!',
    emotion: 'happy',
    background: 'https://i.postimg.cc/MptvzqQh/villain4-21.png',
    characterImage: 'https://i.postimg.cc/jjYFcY2R/vilain4-1.png',
    nextId: 'game_over',
  },
  'thinking_climax': {
    id: 'thinking_climax',
    speaker: 'Thẩm Phán',
    text: 'Thanh tra Thiện, nếu ông không thể đưa ra bằng chứng kết nối trực tiếp hóa chất H-404 với nguồn nước sông, tôi sẽ phải bác bỏ đơn kiện.',
    emotion: 'normal',
    background: 'https://i.postimg.cc/kMcHqH4R/neu.png',
    characterImage: 'https://i.pinimg.com/1200x/4b/9a/c3/4b9ac31ce1d2a08852e9e0877350bfde.jpg',
    nextId: 'cross_exam_5',
  },
  'win_case': {
    id: 'win_case',
    speaker: 'Thanh tra Thiện',
    text: 'Mọi sự dối trá cuối cùng sẽ bị phơi bày trước ánh sáng công lý!',
    emotion: 'happy',
    background: 'https://i.postimg.cc/fR9QKh7N/Chat-GPT-Image-23-52-58-3-thg-5-2026.png',
    characterImage: 'https://i.postimg.cc/ZqcgfsXp/thien1.png',
    nextId: 'final_judgment',
  },
  'final_judgment': {
    id: 'final_judgment',
    speaker: 'Thẩm Phán',
    text: 'Bằng chứng quá đanh thép. Tôi tuyên bố bị cáo Ngọc CÓ TỘI. Nhà máy phải dừng hoạt động và bồi thường thiệt hại cho người dân!',
    emotion: 'surprised',
    background: 'https://i.postimg.cc/kMcHqH4R/neu.png',
    characterImage: 'https://i.pinimg.com/1200x/4b/9a/c3/4b9ac31ce1d2a08852e9e0877350bfde.jpg',
    nextId: 'game_win',
  },
  'game_win': {
    id: 'game_win',
    speaker: 'Thanh tra Thiện',
    text: 'Công lý đã được thực thi. Bà con vùng hạ lưu có thể yên tâm trở lại cuộc sống bình thường.',
    emotion: 'happy',
    background: 'https://i.postimg.cc/fR9QKh7N/Chat-GPT-Image-23-52-58-3-thg-5-2026.png',
    characterImage: 'https://i.postimg.cc/ZqcgfsXp/thien1.png',
    choices: [
      { text: 'Chơi lại', nextId: 'intro_1' },
      { text: 'Về Menu', nextId: 'MENU' }
    ]
  },
  'game_over': {
    id: 'game_over',
    speaker: 'Thẩm Phán',
    text: 'Tố cáo không đủ sức thuyết phục. Tôi bác bỏ đơn kiện của Thanh tra Thiện. Bà Ngọc trắng án!',
    emotion: 'angry',
    background: 'https://i.postimg.cc/kMcHqH4R/neu.png',
    characterImage: 'https://i.pinimg.com/1200x/4b/9a/c3/4b9ac31ce1d2a08852e9e0877350bfde.jpg',
    choices: [
      { text: 'Thử lại', nextId: 'intro_1' },
      { text: 'Về Menu', nextId: 'MENU' }
    ]
  }
};
